services:
  qutu-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: qutu-mysql
    image: qutu-mysql
    ports:
      - 33306:3306
    networks:
      - spring_cloud_default
  qutu-redis:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/redis
    ports:
      - 36379:6379
    restart: always
    container_name: qutu-redis
    hostname: qutu-redis
    networks:
      - spring_cloud_default

  qutu-register:
    build:
      context: ./qutu-register
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 8080:8080
    environment:
      MYSQL_HOST: qutu-mysql
      REDIS_HOST: qutu-redis
    container_name: qutu-register
    hostname: qutu-register
    image: qutu-register
    networks:
      - spring_cloud_default

  qutu-gateway:
    build:
      context: ./qutu-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: qutu-gateway
    hostname: qutu-gateway
    image: qutu-gateway
    environment:
      REDIS_HOST: qutu-redis
      NACOS_HOST: qutu-register
    networks:
      - spring_cloud_default

  qutu-auth:
    build:
      context: ./qutu-auth
    restart: always
    container_name: qutu-auth
    hostname: qutu-auth
    image: qutu-auth
    environment:
      REDIS_HOST: qutu-redis
      NACOS_HOST: qutu-register
    networks:
      - spring_cloud_default

  qutu-upms:
    build:
      context: ./qutu-upms/qutu-upms-biz
    restart: always
    container_name: qutu-upms
    hostname: qutu-upms
    image: qutu-upms
    environment:
      MYSQL_HOST: qutu-mysql
      REDIS_HOST: qutu-redis
      NACOS_HOST: qutu-register
    networks:
      - spring_cloud_default

  qutu-monitor:
    build:
      context: ./qutu-visual/qutu-monitor
    restart: always
    ports:
      - 5001:5001
    container_name: qutu-monitor
    hostname: qutu-monitor
    image: qutu-monitor
    environment:
      NACOS_HOST: qutu-register
    networks:
      - spring_cloud_default

  qutu-codegen:
    build:
      context: ./qutu-visual/qutu-codegen
    restart: always
    container_name: qutu-codegen
    hostname: qutu-codegen
    image: qutu-codegen
    environment:
      MYSQL_HOST: qutu-mysql
      REDIS_HOST: qutu-redis
      NACOS_HOST: qutu-register
    networks:
      - spring_cloud_default

  qutu-quartz:
    build:
      context: ./qutu-visual/qutu-quartz
    restart: always
    image: qutu-quartz
    container_name: qutu-quartz
    environment:
      MYSQL_HOST: qutu-mysql
      REDIS_HOST: qutu-redis
      NACOS_HOST: qutu-register
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge
